services:
  torrentreq:
    build: ./app
    container_name: torrentreq
    expose:
      - "80"
    volumes:
      - /home/jesse/docker/torrentreq/data:/data
    networks:
      - localweb
    restart: unless-stopped

networks:
  localweb:
    external: true
